### ISSUE TITLE
ubuntu20.04 LTS 上下载不了，删掉这些语句块才能用

### ISSUE THREAD

**Issue by 98wb** [mylovesaber/auto_update_github_hosts#1]
https://github.com/mylovesaber/auto_update_github_hosts/blob/e13d4aff985f179457d3fa223d003382c5ea5f23/hosts-tool.sh#L61

**Comment by 98wb** [comment]
删掉了下面这块，手动安放才运行得起来。
求修复，不知原因出在什么地方。


```sh
    if [[ $extraarg =~ "gitee" ]]; then
        _info "从码云下载脚本"
        wget -qO /tmp/hosts-tool https://gitee.com/mylovesaber/auto_update_github_hosts/raw/main/hosts-tool.sh
    elif [[ $extraarg =~ "github" ]]; then
        _info "从 Github 下载脚本"
        wget -qO /tmp/hosts-tool https://raw.githubusercontent.com/mylovesaber/auto_update_github_hosts/master/hosts-tool.sh
    fi
    while true;do
        if [[ -f /tmp/hosts-tool ]];then
            _success "已下载，开始转移到系统程序路径"
            break
        else
            sleep 1
        fi
    done
    mv /tmp/hosts-tool /usr/bin/hosts-tool
    _info "修改权限中..."
    chown root: /usr/bin/hosts-tool
    chmod 755 /usr/bin/hosts-tool
```

**Comment by mylovesaber** [comment]
> 删掉了下面这块，手动安放才运行得起来。 求修复，不知原因出在什么地方。
> 
> ```shell
>     if [[ $extraarg =~ "gitee" ]]; then
>         _info "从码云下载脚本"
>         wget -qO /tmp/hosts-tool https://gitee.com/mylovesaber/auto_update_github_hosts/raw/main/hosts-tool.sh
>     elif [[ $extraarg =~ "github" ]]; then
>         _info "从 Github 下载脚本"
>         wget -qO /tmp/hosts-tool https://raw.githubusercontent.com/mylovesaber/auto_update_github_hosts/master/hosts-tool.sh
>     fi
>     while true;do
>         if [[ -f /tmp/hosts-tool ]];then
>             _success "已下载，开始转移到系统程序路径"
>             break
>         else
>             sleep 1
>         fi
>     done
>     mv /tmp/hosts-tool /usr/bin/hosts-tool
>     _info "修改权限中..."
>     chown root: /usr/bin/hosts-tool
>     chmod 755 /usr/bin/hosts-tool
> ```

等我电脑维修回来再看看，现在手机看着难受(＞＜)

**Comment by mylovesaber** [comment]
如果没记错的话，我这脚本在ubuntu/debian/centos 都测试了能用，可能是因为你大陆机器本身就翻不出去导致的无法下载？大陆很多地方直接从 github 源获取更新的话是无法连接的

我自用的时候都是设置全部从gitee 下载更新，代码更新后会推github，然后 gitee 一键同步，从未出现过这问题，建议你换 gitee 更新

**Comment by mylovesaber** [comment]
> 删掉了下面这块，手动安放才运行得起来。 求修复，不知原因出在什么地方。
> 
> ```shell
>     if [[ $extraarg =~ "gitee" ]]; then
>         _info "从码云下载脚本"
>         wget -qO /tmp/hosts-tool https://gitee.com/mylovesaber/auto_update_github_hosts/raw/main/hosts-tool.sh
>     elif [[ $extraarg =~ "github" ]]; then
>         _info "从 Github 下载脚本"
>         wget -qO /tmp/hosts-tool https://raw.githubusercontent.com/mylovesaber/auto_update_github_hosts/master/hosts-tool.sh
>     fi
>     while true;do
>         if [[ -f /tmp/hosts-tool ]];then
>             _success "已下载，开始转移到系统程序路径"
>             break
>         else
>             sleep 1
>         fi
>     done
>     mv /tmp/hosts-tool /usr/bin/hosts-tool
>     _info "修改权限中..."
>     chown root: /usr/bin/hosts-tool
>     chmod 755 /usr/bin/hosts-tool
> ```

更新了，你测试下？最好是卸载后重新跑一下设置脚本，对于从 github 安装和更新的话新增检测环节，就知道到底是不是你网络问题了，我这边测试好像是正常的，另外新版本增加刷新 dns 功能，所以开始限制系统了，建议看下你的系统是否在脚本支持范围内？如果不在的话请提供下系统名和版本，还有在你系统上有效的刷新 dns 的方法，谢谢
