### ISSUE TITLE
Ubuntu 22.04 提示systemd-resolve: command not found

### ISSUE THREAD

**Issue by storyandwine** [mylovesaber/auto_update_github_hosts#10]
➜ 正在检查系统兼容性...
✓ 当前系统为： Ubuntu 此脚本支持该系统！
➜ 开始安装工具...
➜ 从 GitLab 下载脚本
✓ 已下载，开始转移到系统程序路径
➜ 修改权限中...
✓ 权限修改完成
✓ 工具安装完成
➜ 为原始 hosts 文件文本添加标记并备份为实时更新的 hosts.default...
➜ 为 hosts 文件添加标记中...
✓ 标记完毕
➜ 将原始 hosts 备份为实时更新的 hosts.default...
✓ 备份完毕
➜ 下载最新 GitHub hosts 信息中...
✓ 下载完成
➜ 正在合并并替换成新hosts文件...
✓ 合并替换完成
➜ 正在刷新 DNS 缓存...
/dev/fd/63: line 270: systemd-resolve: command not found
✓ DNS 缓存刷新完成
➜ 清理残留定时任务中...
✓ 清理完成
➜ 添加新定时任务中...
✓ 新定时任务添加完成
✓ GitHub hosts 自动部署和更新工具已安装完成并开启自动更新
✓ 命令行输入：hosts-tool 或 hosts-tool help 即可查看具体控制选项

原因是22.04删除了systemd-resolve
参考链接：https://askubuntu.com/questions/1409726/systemd-resolve-command-not-found-in-ubuntu-22-04-desktop

**Comment by mylovesaber** [comment]
我装台jammy检查下

**Comment by mylovesaber** [comment]
你再测试下看看？ https://github.com/mylovesaber/Tools-Share/commit/34f709d4246eed0488f1938f41b236bba528bd31

**Comment by storyandwine** [comment]
可以了，感恩！！！
