### ISSUE TITLE
DEBIAN12刷新系统缓存似乎有问题

### ISSUE THREAD

**Issue by Yxini** [mylovesaber/auto_update_github_hosts#11]
DEBIAN12运行hosts-tool run 的时候在刷新dns的时候报错

root@armbian:~#` hosts-tool `run
➜ 正在检查系统兼容性...
✓ 当前系统为： Debian 此脚本支持该系统！
➜ 为原始 hosts 文件文本添加标记并备份为实时更新的 hosts.default...
⚠ 发现原始 hosts 文件存在残留的标记信息，开始删除标记信息及以上的所有陈旧信息...
✓ 陈旧信息删除完毕
➜ 为 hosts 文件添加标记中...
✓ 标记完毕
➜ 将原始 hosts 备份为实时更新的 hosts.default...
✓ 备份完毕
➜ 下载最新 GitHub hosts 信息中...
✓ 下载完成
➜ 正在合并并替换成新hosts文件...
✓ 合并替换完成
➜ 正在刷新 DNS 缓存...
Failed to get unit file state for systemd-resolved.service: No such file or directory
/usr/bin/hosts-tool: line 257: /usr/bin/systemd-resolve: No such file or directory
✓ DNS 缓存刷新完成

![图片](https://github.com/mylovesaber/Tools-Share/assets/47093205/f8da898a-b015-43a2-aba0-dce653af94e0)

**Comment by mylovesaber** [comment]
输入以下命令看看各自输出是什么，一行一执行，第一个等待时间可能会很长
```bash
find  /  -name  "*systemd-resolve*"   2>/dev/null
systemctl   list-unit-files   systemd-resolve.service
systemctl --version  |  head -1  #head后面是数字1不是小写字母L
which    resolvectl
```

**Comment by Yxini** [comment]
![图片](https://github.com/mylovesaber/Tools-Share/assets/47093205/549fd224-184b-4396-bbe3-f4e10a89c2ab)
反应是这样的

**Comment by Yxini** [comment]
![图片](https://github.com/mylovesaber/Tools-Share/assets/47093205/a005aa4a-e07d-44e3-a599-0c665cafdf38)
执行后还是一样
