### ISSUE TITLE
能否加入自动刷新dns呢

### ISSUE THREAD

**Issue by BeautyQAQ** [mylovesaber/auto_update_github_hosts#2]
如题, 有时候我运行 `hosts-tool run` 之后还是不能访问GitHub, 但是我手动刷新dns之后就可以, 所以能否在脚本的自动执行当中加入这一块呢? 
系统版本: 阿里云轻量级服务器, centos7

**Comment by mylovesaber** [comment]
把你的操作发一下，我整合下

**Comment by BeautyQAQ** [comment]
需要安装这个`yum install -y nscd`
然后运行`systemctl restart nscd` 或者 `service nscd restart`
**但是我查了一下centos不同版本的命令还不一样, 你可以考虑一下加还是不加**
不加的话在readme中提示一下大家手动刷新吧, 也不麻烦

**Comment by mylovesaber** [comment]
更新了，你测试下？最好是卸载后重新跑一下设置脚本，对于从 github 安装和更新的话新增检测环节，我这边测试好像是正常的

**Comment by BeautyQAQ** [comment]
脚本有点问题, 无法安装了, 在setup.sh的61行, 多了一个 `fi`   ,   报错信息如下:
```shell
bash <(wget --no-check-certificate -qO- https://gitee.com/mylovesaber/auto_update_github_hosts/raw/main/setup.sh) -s gitee
/dev/fd/63: line 62: syntax error near unexpected token `else'
/dev/fd/63: line 62: `    else'
```

**Comment by mylovesaber** [comment]
> 脚本有点问题, 无法安装了, 在setup.sh的61行, 多了一个 `fi` , 报错信息如下:
> 
> ```shell
> bash <(wget --no-check-certificate -qO- https://gitee.com/mylovesaber/auto_update_github_hosts/raw/main/setup.sh) -s gitee
> /dev/fd/63: line 62: syntax error near unexpected token `else'
> /dev/fd/63: line 62: `    else'
> ```

码云和 github 已更新，谢谢提醒
