### ISSUE TITLE
路由器不能吗？

### ISSUE THREAD

**Issue by wuge0** [mylovesaber/auto_update_github_hosts#4]
登录ssh后
![image](https://user-images.githubusercontent.com/31797574/147176695-72c67b9a-f7d1-4c93-8015-c72ded5969e2.jpeg)

**Comment by mylovesaber** [comment]
路由暂时没实机测试，我是用的各种服务器测试的，你这个是 ash，你输入：`which bash` 看看有没有这个 shell？这个图看样子可能是系统没识别到 bash shell 所以返回调用 sh 来执行脚本，而 bash 和 sh 有些写法不太兼容导致，另外运行这个命令看看： `which env`

**Comment by mylovesaber** [comment]
我换了种命令的写法并做了部分调整，你再试试看？关键是看你这系统里面有没有 bash 命令，如果没有的话给个话，我加个功能上去，否则就直接能用了。。。

**Comment by wuge0** [comment]
![2021-12-24 17-50-4](https://user-images.githubusercontent.com/31797574/147342189-cf5111ea-cd6f-4ae8-89c1-c0ee09afc4cd.png)
这是测试结果
路由器系统是 Padavan

**Comment by wuge0** [comment]
![2021-12-24 17-50-4](https://user-images.githubusercontent.com/31797574/147342189-cf5111ea-cd6f-4ae8-89c1-c0ee09afc4cd.png)
这是测试结果
路由器系统是 Padavan

**Comment by wuge0** [comment]
![2021-12-24 17-54-2](https://user-images.githubusercontent.com/31797574/147343338-380af1ea-3cc8-489e-9a95-5bc1ae942171.png)

**Comment by wuge0** [comment]
[MI-R3P /opt/home/admin]# which env
/usr/bin/env
[MI-R3P /opt/home/admin]# which bash
/bin/bash

**Comment by wuge0** [comment]
https://github.com/521xueweihan/GitHub520/issues/57
这个反馈问题里的我也试了不管用

**Comment by wuge0** [comment]
可能要刷Openwrt系统才能

**Comment by mylovesaber** [comment]
路由系统可能和常见 linux 发行版的用法不太一样，我也没有实机测试，你要是不介意的话可以给个联系方式，我远控你路由看看？

**Comment by wuge0** [comment]
可以，微信 2511052
