### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by wuge0** [mylovesaber/auto_update_github_hosts#5]
/var/spool/mail/root  文件每分钟更新一次正常吗
而且文件越来越大，一晚上就快1mb了

![2021-12-23 12-38-13](https://user-images.githubusercontent.com/31797574/147188935-c1d25700-e87e-4afe-bb73-7fbb271cde06.png)

**Comment by wuge0** [comment]
这是centos服务器

**Comment by mylovesaber** [comment]
你 centos 几？你输入 `echo $TERM` 看看？然后这个定时好像有点问题。。我调整下试试，那个文件增大是因为如果有后台运行一个脚本有更新信息但不显示出来，这些信息就会进入 /var/spool/mail/root 中保存，你打开的话会看到的

**Comment by wuge0** [comment]
centos7.9
要怎么解决？

**Comment by mylovesaber** [comment]
脚本的定时我还得测试下，设定的 30min 怎么是 1min 一次。。。
你那个文件增大的问题加个系统定时每分钟都删掉这文件就行了，比如：
```shell
echo "* * * * * root /usr/bin/rm -rf /var/spool/mail/root" >> /etc/crontab
```
另外你输入 `echo $TERM` 看看？

**Comment by wuge0** [comment]
# echo $TERM
xterm

**Comment by mylovesaber** [comment]
重新更新定时了，你运行 `hosts-tool updatefrom gitee` 就可以了
理论上 xterm 的话 tput 可以识别出来的啊。。。你运行这个看看颜色是否正常，是否会有报错：
`tput setaf 2; echo "测试颜色"; tput sgr0`

**Comment by wuge0** [comment]
感谢
已经更新没有报错

**Comment by mylovesaber** [comment]
已经取消了 tput 定义颜色的方式，理论上不存在问题了
