### ISSUE TITLE
自动更新时502的问题

### ISSUE THREAD

**Issue by meteor0027** [mylovesaber/auto_update_github_hosts#6]
pandavan按第2种方法写入自动更新命令，应该是更新没有得到数据时在hosts文件里面写入了下面这部分

![image](https://user-images.githubusercontent.com/24893142/170168099-08969ccb-8f46-4645-9fc2-e87e9a1b1cd6.png)

**Comment by meteor0027** [comment]
后面正常更新到数据，补充在后面
![image](https://user-images.githubusercontent.com/24893142/170168544-50875762-db92-4191-a21a-6b023d946729.png)

**Comment by mylovesaber** [comment]
我这几天有空了把码云平台彻底移除，然后将代码转移到gitlab去，这样大陆用户就应该一切正常了，另外就是这个工具还有一个地方有点不完善：正常工作一段时间后可能把自己给更新没了。。如果你未来遇到了就重新跑一下安装脚本然后hosts-tool run即可，现在别跑，还没切换平台

**Comment by mylovesaber** [comment]
这个工具你暂时先别用，我需要修复下问题

**Comment by meteor0027** [comment]
> 

我没有用工具，我用的是定时命令，在路由器上的

**Comment by mylovesaber** [comment]
pandavan按第2种方法写入自动更新命令，这话指的是哪步操作？

**Comment by meteor0027** [comment]
> pandavan按第2种方法写入自动更新命令，这话指的是哪步操作？

*/30 * * * * autoupdatehosts 我用的这种

**Comment by mylovesaber** [comment]
> > pandavan按第2种方法写入自动更新命令，这话指的是哪步操作？
> 
> */30 * * * * autoupdatehosts 我用的这种

尝试修复了，你可以试试，顺便我给改到一小时一次了，你看看改过的教程吧

**Comment by meteor0027** [comment]
sed -i '/# GitHub520 Host Start/,/# GitHub520 Host End/d' /etc/storage/dnsmasq/hosts
curl https://raw.hellogithub.com/hosts >> /etc/storage/dnsmasq/hosts
sed -i '/<html/d' /etc/storage/dnsmasq/hosts
restart_dns

我已经改过了，我写的是这样的，我在想能不能在 curl时判断是否获取到数据，如果获取 到数据 再进行下一步，没获取到就不执行后面的，因为我发现中间有几次hosts里面是空的，没有数据 的，应该是还没有获取 到数据 就restart_dns了。
另外，我发现有的时候有hosts反而还打不开网页，没有反而能打开，这是什么情况

**Comment by mylovesaber** [comment]
> sed -i '/# GitHub520 Host Start/,/# GitHub520 Host End/d' /etc/storage/dnsmasq/hosts curl https://raw.hellogithub.com/hosts >> /etc/storage/dnsmasq/hosts sed -i '/<html/d' /etc/storage/dnsmasq/hosts restart_dns
> 
> 我已经改过了，我写的是这样的，我在想能不能在 curl时判断是否获取到数据，如果获取 到数据 再进行下一步，没获取到就不执行后面的，因为我发现中间有几次hosts里面是空的，没有数据 的，应该是还没有获取 到数据 就restart_dns了。 另外，我发现有的时候有hosts反而还打不开网页，没有反而能打开，这是什么情况

sed那条命令用我的那个，你那个删不干净只删了一楼图一的第一行，其他都没删掉。

```bash
newIP=$(curl -Ls https://raw.hellogithub.com/hosts|sed '/^</d')
if [ -n "${newIP}" ];then sed -i '/# GitHub520 Host Start/,/# GitHub520 Host End/d' /etc/storage/dnsmasq/hosts;"${newIP}" >> /etc/storage/dnsmasq/hosts;restart_dns;else :;fi
```

以上你试试
空的是因为先删老数据再加新数据，结果老数据删掉了，但新数据没获取到，自然就是空的

有hosts无法打开这点得问那个作者，我这个只是引用他的文本
