### ISSUE TITLE
现在是不能用了吗？

### ISSUE THREAD

**Issue by BeautyQAQ** [mylovesaber/auto_update_github_hosts#8]

**Comment by mylovesaber** [comment]
等我搬迁到新的工具集中，得晚几天，这几天好忙

**Comment by mylovesaber** [comment]
给你个建议，注册个gitlab账户，这是大陆没有被墙的，知名度仅次于github，然后选择你要的github的项目，在gitlab选择导入，然后大陆机器设置gitlab的下载就行

**Comment by mylovesaber** [comment]
迁移了，等更新完功能再通知你

**Comment by mylovesaber** [comment]
已转移并调试完成，可以试试了

https://gitlab.com/mylovesaber/tools-share/-/tree/main/auto-update-github-hosts

**Comment by BeautyQAQ** [comment]
ok，我试了，可以用了，感谢
